# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100_100
  id_prefix: 'wiki:'

wiki_attack_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.wiki_attack_10000
  id_prefix: 'attack:'

wiki_attack_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100-1000
  id_prefix: 'attack:'

webq_20_min4_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_base.wiki_100
  id_prefix: 'attack:'

webq_20_min4_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_base.wiki_1000
  id_prefix: 'attack:'

webq_20_min4_base_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_base.wiki_10000
  id_prefix: 'attack:'

wiki_220k:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.implemented.wiki_220k
  id_prefix: 'wiki:'

webq_20_min15_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min15.wiki_100
  id_prefix: 'attack:'

webq_20_min15_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min15.wiki_1000
  id_prefix: 'attack:'

webq_20_min15_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min15.wiki_10000
  id_prefix: 'attack:'

webq_20_min4_big_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_big.wiki_100
  id_prefix: 'attack:'

webq_20_min4_big_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_big.wiki_1000
  id_prefix: 'attack:'

webq_20_min4_big_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_big.wiki_10000
  id_prefix: 'attack:'

webq_20_min4_small_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_small.wiki_100
  id_prefix: 'attack:'

webq_20_min4_small_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_small.wiki_1000
  id_prefix: 'attack:'

webq_20_min4_small_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min4_small.wiki_10000
  id_prefix: 'attack:'

webq_5_min4_small_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_5_min4_small.wiki_100
  id_prefix: 'attack:'

webq_5_min4_small_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_5_min4_small.wiki_1000
  id_prefix: 'attack:'

webq_5_min4_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_5_min4_base.wiki_100
  id_prefix: 'attack:'

webq_5_min4_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_5_min4_base.wiki_1000
  id_prefix: 'attack:'

webq_5_min4_big_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_5_min4_big.wiki_100
  id_prefix: 'attack:'

webq_5_min4_big_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_5_min4_big.wiki_1000
  id_prefix: 'attack:'

webq_5_min4_small_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_5_min4_small.wiki_10000
  id_prefix: 'attack:'

webq_10_min4_small_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_10_min4_small.wiki_100
  id_prefix: 'attack:'

webq_10_min4_small_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_10_min4_small.wiki_1000
  id_prefix: 'attack:'

webq_10_min4_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_10_min4_base.wiki_100
  id_prefix: 'attack:'

webq_10_min4_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_10_min4_base.wiki_1000
  id_prefix: 'attack:'

webq_10_min4_big_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_10_min4_big.wiki_100
  id_prefix: 'attack:'

webq_10_min4_big_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_10_min4_big.wiki_1000
  id_prefix: 'attack:'

webq_10_min4_small_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_10_min4_small.wiki_10000
  id_prefix: 'attack:'

webq_15_min4_small_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_15_min4_small.wiki_100
  id_prefix: 'attack:'

webq_15_min4_small_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_15_min4_small.wiki_1000
  id_prefix: 'attack:'

webq_15_min4_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_15_min4_base.wiki_100
  id_prefix: 'attack:'

webq_15_min4_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_15_min4_base.wiki_1000
  id_prefix: 'attack:'

webq_15_min4_big_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_15_min4_big.wiki_100
  id_prefix: 'attack:'

webq_15_min4_big_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_15_min4_big.wiki_1000
  id_prefix: 'attack:'

webq_15_min4_small_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_15_min4_small.wiki_10000
  id_prefix: 'attack:'

webq_25_min4_big_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_25_min4_big.wiki_100
  id_prefix: 'attack:'

webq_25_min4_big_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_25_min4_big.wiki_1000
  id_prefix: 'attack:'

webq_25_min4_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_25_min4_base.wiki_100
  id_prefix: 'attack:'

webq_25_min4_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_25_min4_base.wiki_1000
  id_prefix: 'attack:'

webq_25_min4_small_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_25_min4_small.wiki_100
  id_prefix: 'attack:'

webq_25_min4_small_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_25_min4_small.wiki_1000
  id_prefix: 'attack:'

webq_30_min4_big_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_30_min4_big.wiki_100
  id_prefix: 'attack:'

webq_30_min4_big_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_30_min4_big.wiki_1000
  id_prefix: 'attack:'

webq_30_min4_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_30_min4_base.wiki_100
  id_prefix: 'attack:'

webq_30_min4_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_30_min4_base.wiki_1000
  id_prefix: 'attack:'

webq_30_min4_small_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_30_min4_small.wiki_100
  id_prefix: 'attack:'

webq_30_min4_small_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_30_min4_small.wiki_1000
  id_prefix: 'attack:'

webq_50_min4_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_50_min4_base.wiki_100
  id_prefix: 'attack:'

webq_50_min4_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_50_min4_base.wiki_1000
  id_prefix: 'attack:'

webq_20_min8_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min8_base.wiki_100
  id_prefix: 'attack:'

webq_20_min8_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min8_base.wiki_1000
  id_prefix: 'attack:'

webq_20_min16_base_wiki_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min16_base.wiki_100
  id_prefix: 'attack:'

webq_20_min16_base_wiki_1000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.webq_20_min16_base.wiki_1000
  id_prefix: 'attack:'

main_webq_20_min4_base_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.main.main_webq_20_min4_base.wiki_10000
  id_prefix: 'attack:'

main_nq_20_min4_base_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.main.main_nq_20_min4_base.wiki_10000
  id_prefix: 'attack:'

main_curatedtrec_20_min4_base_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.main.main_curatedtrec_20_min4_base.wiki_10000
  id_prefix: 'attack:'

imdb_100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.webq_baseline.imdb.imdb_100

main_squad1_20_min4_base_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.main.main_squad1_20_min4_base.wiki_10000
  id_prefix: 'attack:'

main_trivia_20_min4_base_wiki_10000:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.main.main_trivia_20_min4_base.wiki_10000
  id_prefix: 'attack:'

artordet:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.fine_grained.artordet.wiki_100
  id_prefix: 'attack:'

nn:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.fine_grained.nn.wiki_100
  id_prefix: 'attack:'

prep:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.fine_grained.prep.wiki_100
  id_prefix: 'attack:'

vform:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.fine_grained.vform.wiki_100
  id_prefix: 'attack:'

wchoice:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.fine_grained.wchoice.wiki_100
  id_prefix: 'attack:'