# @package _group_

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train

nq-train-attack-50:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train-attack-50

gene_train-20_min_0-1_nq-train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.gene_train-20_min_0-1_nq-train

gene_train-20_max_0-1_nq-train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.gene_train-20_max_0-1_nq-train

nq-train-20:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train-20

debug-train-1000:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.debug-train-1000

debug-train-100:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.debug-train-100

debug-dev-100:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.debug-dev-100

nq_train_hn1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-adv-hn-train

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-dev

trivia_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train

trivia_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-dev

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

webq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-train

webq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-dev

curatedtrec_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-train

curatedtrec_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-dev

webq_20_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_20_min4_base.train

webq_20_min15_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_20_min15.train

webq_20_min4_big_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_20_min4_big.train

webq_20_min4_small_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_20_min4_small.train

webq_5_min4_small_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_5_min4_small.train

webq_10_min4_small_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_10_min4_small.train

webq_15_min4_small_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_15_min4_small.train

webq_25_min4_small_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_25_min4_small.train

webq_30_min4_small_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_30_min4_small.train

webq_5_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_5_min4_base.train

webq_10_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_10_min4_base.train

webq_15_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_15_min4_base.train

webq_25_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_25_min4_base.train

webq_30_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_30_min4_base.train

webq_50_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_50_min4_base.train

webq_20_min8_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_20_min8_base.train

webq_20_min16_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.webq_baseline.webq_20_min16_base.train

main_webq_20_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.main.main_webq_20_min4_base.train

main_nq_20_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.main.main_nq_20_min4_base.train

main_curatedtrec_20_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.main.main_curatedtrec_20_min4_base.train

main_trivia_20_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.main.main_trivia_20_min4_base.train

main_squad1_20_min4_base_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.main.main_squad1_20_min4_base.train

artordet:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.fine_grained.artordet.train

nn:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.fine_grained.nn.train

prep:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.fine_grained.prep.train

vform:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.fine_grained.vform.train

wchoice:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.fine_grained.wchoice.train